### ISSUE TITLE
Error using PeakFit/fit

### ISSUE THREAD

**Issue by serg499** [heriantolim/PeakFit#3]
Hi!
Please help with running your library/examples.
I used `addpackage('MatCommon','MatGraphics','PeakFit');`
When I try to launch VO2_raman example and MatLab gives an error on the line:
`S.Fit = PeakFit(S.Data, 'Window', [100, 900], 'PeakShape', 'Lorentzian', ...
    'CenterLow', [521, 145, 198, 224, 258, 304, 310, 336, 387, 394, 430, 503, 588, 615, 665, 827], ...
    'CenterUp', [524, 151, 202, 228, 263, 306, 315, 342, 394, 402, 450, 506, 597, 625, 675, 837], ...
    'WidthUp', [4, 14, 10, 8, 10, 10, 10, 10, 18, 20, 40, 20, 30, 40, 20, 30], ...
    'BaselinePolyOrder', 1);`

So I'm getting this error:
```
Error using PeakFit/fit
Method 'fit' is not defined for class 'PeakFit' or is removed from MATLAB's search path.

Error in PeakFit (line 356)
            obj = fit(obj);

Error in VO2_Raman (line 18)
S.Fit = PeakFit(S.Data, 'Window', [100, 900], 'PeakShape', 'Lorentzian', ...
```

So please help me to find an error.
Thank you!

**Comment by serg499** [comment]
It was an issue with setting the correct values to the path folders. I haven't added class folders before. They shouldn't be in the path, only the parent folder.

**Comment by heriantolim** [comment]
Sorry, I am not on GitHub most of the times. I'm glad you solved your problem :)
